### ISSUE TITLE
AIMRequest simplexml_load_string chokes

### ISSUE THREAD

**Issue by marionnewlevant** [thephpleague/omnipay-authorizenet#112] opened 2018-05-23 05:52 UTC
We are trying to get payments to work using the authorize.net gateway.

It looks like we managed to send an AIMRequest, and got back an AIMResponse
omnipay/authorizenet/src/Message/AIMResponse.php

The __construct there is:

```
    public function __construct(AbstractRequest $request, $data)
    {
        // Strip out the xmlns junk so that PHP can parse the XML
        $xml = preg_replace('/<createTransactionResponse[^>]+>/', '<createTransactionResponse>', (string)$data);

        try {
            $xml = simplexml_load_string($xml, 'SimpleXMLElement', LIBXML_NOWARNING);
        } catch (\Exception $e) {
            throw new InvalidResponseException();
        }

        if (!$xml) {
            throw new InvalidResponseException();
        }

        parent::__construct($request, $xml);
    }
```

I am pretty sure that the value of $xml is:

```text
<HTML><BODY><H3>The following errors have occurred.</H3>(13) The merchant login ID or password is invalid or the account is inactive.<BR></BODY></HTML>

and then the simplexml_load_string throws this warning:
PHP warning
simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: BR line 1 and BODY
/home/embark99/staging/goldpawseries/site/craft/plugins/commerce/vendor/omnipay/authorizenet/src/Message/AIMResponse.php(35)
```

simplexml_load_string is unhappy about the invalid xml in that <BR> tag.

I'm not sure what exactly you can do, but it would be nice if somehow that error message didn't get so thoroughly swallowed.

------
*JDJ: edited for formatting*

**Comment by lukeholder** [comment] 2018-05-23 07:05
@marionnewlevant could you put code quotes around the response html in your issue above. thanks.

**Comment by judgej** [comment] 2018-05-23 09:44
I think the request message needs to check the response `Content-Type` before creating the `AIMResponse` message. It it's not `application/xml` (or something like that) than it should throw an exception, or maybe create an `AIMResponse` with a default XML document.

**Comment by judgej** [comment] 2018-05-23 10:02
Strangely, with an invalid merchant ID, I get this:

```
getResultCode(): 0
getReasonCode(): E00007
getMessage(): User authentication failed due to invalid authentication values.
```

i.e. I get valid XML back. @marionnewlevant do you have any further details of what you did not have set up properly? Also PHP version and this driver version (2.x or 3.x - `composer show` will tell you this).

**Comment by judgej** [comment] 2018-05-23 10:07
@lukeholder as an aside, and if you are interested, I'm putting together a completely new driver to replace all the deprecated Authorize.Net APIs [here](https://github.com/academe/Omnipay-AuthorizeNetApi). It's been a bit slow because of other commitments, but it's coming along. It handles messaging in JSON, and offloads the message structure to a separate package.

**Comment by judgej** [comment] 2018-12-30 23:35
Is this still a problem? It's not something I have managed to reproduce.

**Comment by judgej** [comment] 2019-04-27 22:36
I'm going to close this as it has not been reproducable, and may have been fixed on the back of other fixes. Please reopen if it is still an issue.

**Closed by judgej** 2019-04-27 22:36 UTC
