### ISSUE TITLE
Array to string conversion in CIMAbstractResponse

### ISSUE THREAD

**Issue by javabudd** [thephpleague/omnipay-authorizenet#105] opened 2018-01-30 22:55 UTC
The function getResultCode in the CIMAbstractResponse class (line 59) is doing an array to string conversion which now throws a fatal error in PHP 7.2.

$result should be evaluated before being casted to a string

**Comment by judgej** [comment] 2018-01-31 01:28
https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/CIMAbstractResponse.php#L61

Is this about the changes to operator precedence? This is the line now:

    $result = (string)$this->data['messages'][0]['resultCode'];

TBH I'm not sure why the value is cast to a string, since you can't cast an array to a string anyway. If you take out the `(string)` completely, does it work for you? I've not got PHP7.2 handy to try it on, though we could enable on travis.

**Comment by judgej** [comment] 2018-01-31 02:00
Not sure where the problem is exactly, but it seems to be the way the XML is parsed. This is what the response looks like in 7.1:

```php
array(2) {
  ["messages"]=>
  array(1) {
    [0]=>
    array(2) {
      ["resultCode"]=>
      string(2) "Ok"
      ["message"]=>
      array(1) {
        [0]=>
        array(2) {
          ["code"]=>
          string(6) "I00001"
          ["text"]=>
          string(11) "Successful."
        }
      }
    }
  }
```

Then in 7.2 the response looks like this:

```php
array(2) {
  ["messages"]=>
  array(1) {
    [0]=>
    array(2) {
      ["resultCode"]=>
      array(1) {
        [0]=>
        array(0) {
        }
      }
      ["message"]=>
      array(1) {
        [0]=>
        array(2) {
          ["code"]=>
          array(1) {
            [0]=>
            array(0) {
            }
          }
          ["text"]=>
          array(1) {
            [0]=>
            array(0) {
            }
          }
        }
      }
    }
  }
```

Note all the string nodes have tuned into empty arrays :-/

**Comment by judgej** [comment] 2018-01-31 02:21
I suspect the issue is in the [xml2array](https://github.com/thephpleague/omnipay-authorizenet/blob/master/src/Message/CIMAbstractResponse.php#L156) method, but need to explore a little further to see what is really happening. Between 7.1 and 7.2, this method behaves very differently.

**Comment by javabudd** [comment] 2018-01-31 14:53
Good find, I'll try poking around as well

**Comment by judgej** [comment] 2018-01-31 14:57
I won't have time to look until I get home (about 8 hours). I cannot find anything on SO or the docs that indicate SimpleXML has changed in 7.2, except for a few bug fixes. So that may point more towards where the XML is parsed. But I may be completely off there.

**Comment by judgej** [comment] 2018-02-04 16:45
There is a PR to play with here. It uses the much simpler json_decode of a json_encode to convert the parsed XML object to an array. This does change the structure of the resulting array slightly. It is failing all travis tests on 7.2 due to deprecated code in phpunit (3.9). I'm sure there will be a way to disable some cs code checks for PHP 7.2 only, or perhaps the travis config is not pointing phpcs at the correct directory to scan - not sure.

**Comment by judgej** [comment] 2018-12-31 14:35
A fix has been in place since January 2017 (for version 3.0.0) that changes the way the XML is decoded to an array. That was probably merged in accidentally, but it does not seem to have raised any issues, so I'm going to close this issue.

If I've overlooked anything here, please reopen or raise a new issue if there are other subsequent side-effects. The JSON encode/decode technique used to convert the XML to an array does have its limits (e.g. not properly handling attributes), but the XML supplied by this gateway does not seem to hit it.

**Closed by judgej** 2018-12-31 14:35 UTC
